# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Fachinformatiker-Forum Fulda
logo:               https://github.com/joergre/fachinformatiker-forum/blob/gh-pages/logo.jpg?raw=true# Logo image URL
email:              joerg@reuter.sc
description:        Alles über IT.
baseurl:            '/fachinformatiker-forum' # The subpath of your site, e.g. /blog
url:                'https://joergre.github.io' # The base hostname & protocol for your site
github_username:    joergre
twitter_username:   joergreu
instagram_username: jorgreuter

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             Jörg Reuter
    bio:              Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar:         https://en.gravatar.com/forsthaus
    email:            joerg@reuter.sc
    website:          https://joergre.github.io/fachinformatiker-forum/
    github_username:  joergre
    twitter_username: joergereu
